version: 2
jobs:
  build:
    #- run: https://github.com/decrypt1234/the-example-app.nodejs.git
 #   docker:
 #     - image: cypress/base:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: clone-e2e-test
          command: https://github.com/decrypt1234/the-example-app.nodejs.git/test/run-e2e-test.js
      - run:
          name: install-un-e2e-test.js-test
          command: cd ./test/un-e2e-test.js && npm install
      - run:
          name: test
          command: npm run test
      - store_artifacts:
          path: /tmp/artifact-1

          destination: artifact-file-cypress-result_`date +%Y-%m-%d_%H-%M-%S`

      - store_artifacts:
          path: /tmp/artifacts

